# Generated by Django 3.2.4 on 2021-06-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='bought_date',
            new_name='boughtdate',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='expirary_date',
            new_name='expirarydate',
        ),
    ]
