# Generated by Django 3.2.4 on 2021-06-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_remove_menu_expirarydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='boughtdate',
            new_name='date',
        ),
    ]
