# Generated by Django 3.1.2 on 2021-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_rename_boughtdate_menu_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='menu',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
