# Generated by Django 3.1.2 on 2021-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_auto_20210625_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='expires',
            new_name='expirydate',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created',
        ),
        migrations.AddField(
            model_name='menu',
            name='manufacturedate',
            field=models.DateField(null=True),
        ),
    ]
