# Generated by Django 3.2.5 on 2021-07-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_auto_20210709_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='updated_at',
            new_name='updatedat',
        ),
    ]
