# Generated by Django 3.1.2 on 2021-07-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stockcart',
            new_name='cart',
        ),
    ]
