# Generated by Django 3.2.5 on 2021-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20210709_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enabled_status',
            field=models.BooleanField(default=True),
        ),
    ]
